version: '3.7'
services:
 proyectos-microservicio01:
  container_name: 'proyectos-microservicio01'
  image: luis1997fer/proyectos-microservicio:v1
  ports:
   - "4001"
  networks:
   - proyectos-microservicio
  environment:
   CONTAINER_HOST: proyectos-microservicio01
 proyectos-microservicio02:
  container_name: 'proyectos-microservicio02'
  image: luis1997fer/proyectos-microservicio:v1
  ports:
   - "4001"
  networks:
   - proyectos-microservicio
  environment:
   CONTAINER_HOST: proyectos-microservicio01
load-balancer:
  container_name: 'load-balancer'
  image: load-balancer:v1
  build:
    context: ./load-balancer
  ports:
   - "8082:80"
  networks:
   - proyectos-microservicio
  depends_on:
   - proyectos-microservicio01
   - proyectos-microservicio02
  restart: always  
networks:
 proyectos-microservicio:

 