version: '3.7'
services:
 proyectos-microservicio:
  container_name: 'proyectos-microservicio'
  image: luis1997fer/proyectos-microservicio:v1
  build:
   context: .
  ports:
   - "5001:4001"
  networks:
   - proyectos-microservicio
networks:
 proyectos-microservicio:

 